"""
Django settings for gestao_ferias project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path

if getattr(sys, 'frozen', False):
    # Executando como executável PyInstaller
    ROOT_DIR = Path(sys.executable).parent
    BASE_DIR = Path(sys._MEIPASS)
    DEBUG = True  # Ou False, se preferir em produção
else:
    # Executando normalmente
    BASE_DIR = Path(__file__).resolve().parent.parent
    ROOT_DIR = BASE_DIR
    DEBUG = True  # Mantenha True durante o desenvolvimento

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-zy+9gjrae4kz*zg15n#utb-jtgtlc3%&s-!pp-l3a@+(3crrd("

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:63150']

# Application definition

INSTALLED_APPS = [
    # Apps padrão do Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Seus apps
    'gestao_colaboradores',
    'django_filters',
]

MIDDLEWARE = [
    # Middleware padrão do Django
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "gestao_ferias.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ROOT_DIR / 'gestao_colaboradores' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Context processors padrão
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "gestao_ferias.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(ROOT_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Validadores padrão do Django
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = ROOT_DIR / 'staticfiles'

if not DEBUG:
    # Quando em produção ou empacotado
    STATICFILES_DIRS = [BASE_DIR / 'gestao_colaboradores' / 'static']
else:
    # Durante o desenvolvimento
    STATICFILES_DIRS = [BASE_DIR / 'gestao_colaboradores' / 'static']


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"