# Generated by Django 5.0.6 on 2024-10-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "graduacao",
                    models.CharField(
                        choices=[
                            ("Capitão", "Capitão"),
                            ("Tenente", "Tenente"),
                            ("Subtenente", "Subtenente"),
                            ("1º Sargento", "1º Sargento"),
                            ("2º Sargento", "2º Sargento"),
                            ("3º Sargento", "3º Sargento"),
                            ("Cabo", "Cabo"),
                            ("Soldado", "Soldado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero_re", models.IntegerField(unique=True)),
                ("data_promocao", models.DateField(blank=True, null=True)),
                ("mes1_preferencia", models.CharField(max_length=20)),
                ("mes2_preferencia", models.CharField(max_length=20)),
                ("mes3_preferencia", models.CharField(max_length=20)),
            ],
        ),
    ]
