# Generated by Django 5.0.6 on 2024-10-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="mes1_preferencia",
            field=models.CharField(
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="mes2_preferencia",
            field=models.CharField(
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="mes3_preferencia",
            field=models.CharField(
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="numero_re",
            field=models.IntegerField(max_length=6, unique=True),
        ),
    ]
