# Generated by Django 5.0.6 on 2024-10-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0002_alter_colaborador_mes1_preferencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="numero_re",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
