# Generated by Django 5.1.2 on 2024-10-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0002_alter_colaborador_numero_re"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="mes_alocado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
