# Generated by Django 5.1.2 on 2024-10-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0003_colaborador_mes_alocado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="numero_re",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
