# Generated by Django 5.1.2 on 2024-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0006_configuracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="quinzena1_dia",
            field=models.IntegerField(
                blank=True, choices=[(1, "1 a 15"), (2, "16 a 30")], null=True
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="quinzena1_mes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="quinzena2_dia",
            field=models.IntegerField(
                blank=True, choices=[(1, "1 a 15"), (2, "16 a 30")], null=True
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="quinzena2_mes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
