# Generated by Django 5.1.2 on 2024-10-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0008_remove_colaborador_quinzena1_dia_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colaborador",
            old_name="quinzena1_mes",
            new_name="quinzena1_tipo",
        ),
        migrations.RenameField(
            model_name="colaborador",
            old_name="quinzena2_mes",
            new_name="quinzena2_tipo",
        ),
        migrations.RemoveField(
            model_name="colaborador",
            name="quinzena1",
        ),
        migrations.RemoveField(
            model_name="colaborador",
            name="quinzena2",
        ),
    ]
