# Generated by Django 5.1.2 on 2024-10-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestao_colaboradores",
            "0009_rename_quinzena1_mes_colaborador_quinzena1_tipo_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="colaborador",
            old_name="quinzena1_tipo",
            new_name="quinzena1_mes",
        ),
        migrations.RenameField(
            model_name="colaborador",
            old_name="quinzena2_tipo",
            new_name="quinzena2_mes",
        ),
        migrations.AddField(
            model_name="colaborador",
            name="tipo_ferias",
            field=models.CharField(
                choices=[("mensal", "Mensal"), ("quinzenal", "Quinzenal")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
