# Generated by Django 5.1.2 on 2025-03-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0012_alter_colaborador_mes1_preferencia_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colaborador",
            old_name="data_promocao",
            new_name="data_ingresso_pm",
        ),
        migrations.AddField(
            model_name="colaborador",
            name="classificacao_concurso",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="data_ultima_promocao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
