# Generated by Django 5.1.2 on 2025-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestao_colaboradores",
            "0013_rename_data_promocao_colaborador_data_ingresso_pm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="inicio_ferias1",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="inicio_ferias2",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="inicio_ferias3",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="inicio_ferias_alocado",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="inicio_quinzena1",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="inicio_quinzena1_alocado",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="inicio_quinzena2",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="inicio_quinzena2_alocado",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="quinzena1_alocada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="quinzena2_alocada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
