# Generated by Django 5.1.2 on 2025-03-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0015_colaborador_inicio_quinzena3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="alocacao_provisoria",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao1_inicio",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao1_mes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao1_tipo",
            field=models.CharField(
                blank=True,
                choices=[("mensal", "Mensal"), ("quinzenal", "Quinzenal")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao2_inicio",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao2_mes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao2_tipo",
            field=models.CharField(
                blank=True,
                choices=[("mensal", "Mensal"), ("quinzenal", "Quinzenal")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao3_inicio",
            field=models.CharField(
                blank=True,
                choices=[("1", "Dia 1"), ("15", "Dia 15")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao3_mes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Janeiro", "Janeiro"),
                    ("Fevereiro", "Fevereiro"),
                    ("Março", "Março"),
                    ("Abril", "Abril"),
                    ("Maio", "Maio"),
                    ("Junho", "Junho"),
                    ("Julho", "Julho"),
                    ("Agosto", "Agosto"),
                    ("Setembro", "Setembro"),
                    ("Outubro", "Outubro"),
                    ("Novembro", "Novembro"),
                    ("Dezembro", "Dezembro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="opcao3_tipo",
            field=models.CharField(
                blank=True,
                choices=[("mensal", "Mensal"), ("quinzenal", "Quinzenal")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="preferencias_originais",
            field=models.TextField(blank=True, null=True),
        ),
    ]
