# Generated by Django 5.0.6 on 2025-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0016_colaborador_alocacao_provisoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="graduacao",
            field=models.CharField(
                choices=[
                    ("Coronel", "Coronel"),
                    ("Tenente-Coronel", "Tenente-Coronel"),
                    ("Major", "Major"),
                    ("Capitão", "Capitão"),
                    ("1º Tenente", "1º Tenente"),
                    ("2º Tenente", "2º Tenente"),
                    ("Asp Oficial", "Asp Oficial"),
                    ("Subtenente", "Subtenente"),
                    ("1º Sargento", "1º Sargento"),
                    ("2º Sargento", "2º Sargento"),
                    ("3º Sargento", "3º Sargento"),
                    ("Cabo", "Cabo"),
                    ("Soldado", "Soldado"),
                ],
                max_length=20,
            ),
        ),
    ]
