# Generated by Django 5.0.6 on 2025-04-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_colaboradores", "0017_colaborador_data_nascimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="precisa_realocar",
            field=models.BooleanField(default=False),
        ),
    ]
